agent:
  templates:
    system_template: |-
      You are a helpful assistant that can interact with a computer to solve tasks.
    instance_template: |-
      We're solving the following security issue:
      ## ISSUE:
      {{problem_statement}}

      ## INSTRUCTIONS:
      You'll solve this issue using the terminal session that's now active in the repository's root directory.
      IMPORTANT: INCLUDE EXACTLY ONE TOOL CALL/FUNCTION CALL PER RESPONSE.
      When your changes are complete, run the `submit` command.
      No interactive commands (python, vim, gdb, etc.) are allowed - write scripts instead.

      ## KEY TIPS:
      1. If a command fails, check if the current directory is the repository root directory
      2. Use `goto <line_number>` to navigate large files efficiently
      3. Always check the current open file and working directory before commands
      4. Verify code after editing to ensure correct syntax and indentation
      5. When changing code, explain the problem in the code, your fix, and how it preserves functionality

      ## WORKFLOW:
      1. Reproduce the bug with `secb repro`
      2. Locate relevant code using `find`, `search`, and `open` commands
      3. Edit files with the `change` command (NOT `edit`) and MAINTAIN CORRECT INDENTATION
      4. Test your fix: first run `secb build` then `secb repro` (NOTE: the working directory is the repository root)
      5. Submit changes with the `submit` command

      (Open file: {{open_file}})
      (Current directory: {{working_dir}})
      bash-$
    next_step_template: |-
      {{observation}}
      (Open file: {{open_file}})
      (Current directory: {{working_dir}})
      bash-$
    next_step_no_output_template: |-
      Your command ran successfully and did not produce any output.
      (Open file: {{open_file}})
      (Current directory: {{working_dir}})
      bash-$
  tools:
    execution_timeout: 600
    env_variables:
      WINDOW: 100
      OVERLAP: 2
    bundles:
      - path: tools/registry
      - path: tools/defaults
      - path: tools/search
      - path: tools/change
    enable_bash_tool: true
    parse_function:
      type: function_calling
  history_processors:
    - type: last_n_observations
      n: 5
